### ISSUE TITLE
Demo Dataset link is broken

### ISSUE THREAD

**Issue by AbhijitKuma** [thu-vis/OoDAnalyzer#3]
I am not able to download data using the link provided on github :https://pan.baidu.com/s/1kFXlgW3pogn2NfSkw2Vyrw
Please provide the correct link.

**Comment by chencjGene** [comment]
The link (Baiduyun) works well. Maybe Baiduyun cannot be accessed outside of China. I also uploaded it to Google Drive: https://drive.google.com/file/d/1-QP8DVa5dwOXgFVejassJUlRzYLK5v7o/view?usp=sharing. Pls try this link.

**Comment by AbhijitKuma** [comment]
Thanks a lot. I can download it.
