### ISSUE TITLE
Run under Ubuntu

### ISSUE THREAD

**Issue by anastasia-spb** [thu-vis/OoDAnalyzer#4]
Could you please share sources for ``scripts/utils/knnDll.dll``? I would like to run an analyzer tool under Ubuntu.

**Comment by chencjGene** [comment]
Hello,

knnDll.dll is an API for quick kNN queries. It is not necessary to use this DLL. I have modified the code. It should be able to run under Ubuntu.

Best,

Changjian

**Comment by anastasia-spb** [comment]
Hello,
thank you for answer. I was able to launch analyzer on Ubuntu. However for Ubuntu launch it's necessary to comment out https://github.com/thu-vis/OoDAnalyzer/commit/929f6f34df0d95372633d3574c3c46bd72a352dc#diff-8f0db56dd0dbc1ca4d0209b7d3c17dd1c2bcfa1c687ca1be5a46bfc46a93157eR121-R123. Otherwise ``dist`` are empty. Exception is caught inside https://github.com/thu-vis/OoDAnalyzer/blob/929f6f34df0d95372633d3574c3c46bd72a352dc/scripts/utils/sampling_utils.py#L51.

**Comment by chencjGene** [comment]
Thanks for the feedback. I have fixed this (https://github.com/thu-vis/OoDAnalyzer/commit/2f78c3e7ec6a70a3fc6755b1514bf627e5c626ca).
